
import Classic_Travertine from"../../Photos/Classic Travertine.jpg"
import Ivory_Travertine from"../../Photos/Ivory Travertine.jpg"
import Jerusalem_Stone from"../../Photos/Jerusalem Stone.webp"
import treistabeige from"../../Photos/trestabeige.jpg"
import Triesta_gray from"../../Photos/Triesta gray marble.jpg"
import Melli_Grey_Marble from"../../Photos/Melli Grey Marble.jpg"
import Sylvia_Beida_Marble from"../../Photos/Sylvia white.jpg"
import Sylvia_green_Marble from"../../Photos/Sylvia green.jpg"
import SunnyMeniamarble from"../../Photos/Sunny Menia marble.jpg"
import imperial_marble from"../../Photos/imperial-marble.webp"
import galala_marble from"../../Photos/galala marble.jpg"
import catrina_marble from"../../Photos/catrina marble.jpg"
import NewHalayeb from"../../Photos/New Halayeb Granite.jpg"
import Halayeb from"../../Photos/Halayeb.jpg"
import GandolaGranite from"../../Photos/Gandola Granite.jpg"
import SherkaGray from"../../Photos/Sherka Gray.jpg"
import WhiteSafagaGranite from"../../Photos/White Safaga Granite.webp"
import RedAswanGranite from"../../Photos/Red Aswan Granite.jpg"
import RosaElnasrGranite from"../../Photos/Rosa Elnasr Granite.jpg"
import RosaHodiGranite from"../../Photos/Rosa Hodi Granite.jpg"
import RedHurghadaGranite from"../../Photos/Red Hurghada Granite.jpg"
import BrownQuseirGranite from"../../Photos/bonyoser.jpg"
import FantasticWhiteGranite from"../../Photos/fantastic white.jpg"
import KemetBrown from"../../Photos/Kemet Brown.jpg"
import VerdeGreenGranite from"../../Photos/verdi green.jpg"
import BlackBasaltGranite from"../../Photos/BlackBasaltGranite.jpg"
import SplitFaceMarble from"../../Photos/Split Face Marble.jpg"
import SplitFaceMarble2 from"../../Photos/sina bryl 2.jpg"


export const PRODUCTS = {
  marble: [
    {
      id: 1,
      name: {
        en: "Sinai Pearl Marble",
        ar: "رخام  سينا بريل",
      },
      image:treistabeige
      
    },
    {
      id: 2,
      name: {
        en: "Triesta gray marble",
        ar: "رخام تريستا رمادي",
      },
      image:Triesta_gray
      },
    {
      id: 3,
      name: {
        en: "Melli Grey Marble",
        ar: "رخام ميلي رمادي",
      },
      image: Melli_Grey_Marble,
    },
    {
      id: 4,
      name: {
        en: "Sylvia Beida Marble",
        ar: "رخام سيلفيا بيضاء",
      },
      image: Sylvia_Beida_Marble,
    },
    {
      id: 5,
      name: {
        en: "Sylvia green marble",
        ar: "رخام سيلفيا أخضر",
      },
      image: Sylvia_green_Marble,
        
    },
    {
      id: 6,
      name: {
        en: "Sunny Menia marble",
        ar: "رخام صني منيا",
      },
      image: SunnyMeniamarble,
        
    },
    {
      id: 7,
      name: {
        en: "Imperial Marble",
        ar: "رخام امبريال ",
      },
      image: imperial_marble,
        
    },
    {
      id: 8,
      name: {
        en: "Galala marble",
        ar: "رخام جلالة ",
      },
      image: galala_marble,
        
    },
    {
      id: 9,
      name: {
        en: "Catrina Marble",
        ar: "رخام كاترينا",
      },
      image: catrina_marble,
        
    },
    {
      id: 10,
      name: {
        en: "Sunny Menia split face Marble",
        ar: "رخام وش جبل",
      },
      image: SplitFaceMarble,
        
    },
    {
      id: 11,
      name: {
        en: "Sinai Pearl split face Marble 2",
        ar: "رخام وش جبل 2",
      },
      image: SplitFaceMarble2,
        
    },
    
  ],

  granite: [
    {
      id: 1,
      name: {
        en: "New Halayeb Granite",
        ar: "جرانيت حلايب الجديد",
      },
      image:
        NewHalayeb,
    },
    {
      id: 2,
      name: {
        en: "Halayeb Granite",
        ar: "جرانيت حلايب",
      },
      image:Halayeb
        ,
    },
    {
      id: 3,
      name: {
        en: "Gandola Granite",
        ar: "جرانيت جاندولا",
      },
      image: GandolaGranite
    },
    {
      id: 4,
      name: {
        en: "Sherka Gray",
        ar: "جرانيت شركة رمادي",
      },
      image:SherkaGray
        ,
    },
    {
      id: 5,
      name: {
        en: "White Safaga Granite",
        ar: "جرانيت سفاجا أبيض",
      },
      image: WhiteSafagaGranite
        ,
    },
    {
      id: 6,
      name: {
        en: "Red Aswan Granite",
        ar: "جرانيت احمر اسوان",
      },
      image: RedAswanGranite
        ,
    },
    {
      id: 7,
      name: {
        en: "Rosa Elnasr Granite",
        ar: "جرانيت روزا النصر",
      },
      image: RosaElnasrGranite
        ,
    },
    {
      id: 8,
      name: {
        en: "Rosa Hodi Granite",
        ar: "جرانيت روزا هودي",
      },
      image: RosaHodiGranite
        ,
    },
    {
      id: 9,
      name: {
        en: "Red Hurghada Granite",
        ar: " جرانيت احمر الغردقة",
      },
      image: RedHurghadaGranite
        ,
    },
    {
      id: 10,
      name: {
        en: "Brown Quseir Granite",
        ar: " جرانيت بني قصير",
      },
      image: BrownQuseirGranite
        ,
    },
    {
      id: 11,
      name: {
        en: "Fantastic White Granite",
        ar: " جرانيت فنتاستك وايت",
      },
      image: FantasticWhiteGranite
        ,
    },
    {
      id: 12,
      name: {
        en: "Kemet Brown Granite",
        ar: " جرانيت بني كيمت",
      },
      image: KemetBrown
        ,
    },
    {
      id: 13,
      name: {
        en: "Verde Green Granite",
        ar: " جرانيت فيردي أخضر",
      },
      image: VerdeGreenGranite
        ,
    },
    {
      id: 14,
      name: {
        en: "Black basalt Granite",
        ar: " جرانيت بازلت أسود",
      },
      image: BlackBasaltGranite
        ,
    },
  ],

  
  

  
};